#!/bin/bash


function help {
  echo "[key_word]"
}

if [ $# -eq 1 ]
then
  export KEY_WORD="$1"
else
  help
  exit
fi

echo "streaming $KEY_WORD"
python twitter_streaming.py > data/twitter_$KEY_WORD.txt
