#!/bin/bash


function help {
  echo '["keyword"]'
}

if [ $# -eq 1 ]
then
  export KEYWORD="$1"
else
  help
  exit
fi

profix=`echo $KEYWORD|cut -c1-3`


if [ -f "twitter_$profix.txt" ]
then
  cp twitter_$profix.txt twitter_$profix.txt.bak
  rm twitter_$profix.txt
fi

python twitter_streaming.py > twitter_$profix.txt
